/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FileTransfer;

import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {

    public final static boolean DEBUGGING = true;

    @Override
    public void start(Stage primaryStage) throws Exception {
        if (DEBUGGING){
            System.out.println("Hello World!");
        }

        Group root = new Group();
        primaryStage.setScene(new Scene(root));
        primaryStage.show();
    }

    


}
